export  const menuList:AnyObj[] = [
  {
    id: "10",
    name: "按钮类型",
    url: "/inp",
    icon: "menu-button",
    children: [
      {
        id: "11",
        name: "普通按钮",
        url: "/inp/button",
        icon: "",
        children: [],
      },
      {
        id: "12",
        name: "页面布局",
        url: "/inp/layout",
        icon: "",
        children: [],
      },
      {
        id: "13",
        name: "输入框类型",
        url: "/inp/input",
        icon: "",
        children: [],
      },
      {
        id: "14",
        name: "复选框",
        url: "/inp/checkbox",
        icon: "",
        children: [],
      },
      {
        id: "15",
        name: "搜索",
        url: "/inp/search",
        icon: "",
        children: [],
      },
      {
        id: "16",
        name: "文本框",
        url: "/inp/textarea",
        icon: "",
        children: [],
      },
      {
        id: "17",
        name: "文件上传",
        url: "/inp/fileInp",
        icon: "",
        children: [],
      },
    ],
  },
  {
    id: "20",
    name: "列表类型",
    url: "/table",
    icon: "table",
    children: [
      {
        id: "21",
        name: "普通表格",
        url: "/table/list",
        icon: "",
        children: [],
      },
      {
        id: "22",
        name: "树形表格",
        url: "/table/tree",
        icon: "",
        children: [],
      },
      {
        id: "23",
        name: "固定表格",
        url: "/table/frozen",
        icon: "",
        children: [],
      },
    ],
  },
  {
    id: "40",
    name: "数据结构",
    url: "/dataType",
    icon: "dataType",
    children: [
      {
        id: "41",
        name: "二叉树",
        url: "/blog/bintree",
        icon: "",
        children: [],
      },
      {
        id: "42",
        name: "自由树",
        url: "/blog/tree",
        icon: "",
        children: [],
      },
    ],
  },
  {
    id: "50",
    name: "数据加载",
    url: "/loading",
    icon: "loading",
    children: [
      {
        id: "51",
        name: "加载中",
        url: "/loading/index",
        icon: "",
        children: [],
      },
      {
        id: "52",
        name: "页面崩溃",
        url: "/loading/crash",
        icon: "",
        children: [],
      },
      {
        id: "53",
        name: "空数据与图标",
        url: "/loading/empty",
        icon: "",
        children: [],
      },
    ],
  },
  {
    id: "60",
    name: "下拉框",
    url: "/combo",
    icon: "combo",
    children: [
      {
        id: "61",
        name: "列表下拉框",
        url: "/combo/list",
        icon: "",
        children: [],
      },
      {
        id: "62",
        name: "树形下拉框",
        url: "/combo/tree",
        icon: "",
        children: [],
      },
      {
        id: "63",
        name: "日历",
        url: "/combo/calendar",
        icon: "",
        children: [],
      },
    ],
  },
  {
    id: "70",
    name: "模态框",
    url: "/modal",
    icon: "alert",
    children: [
      {
        id: "71",
        name: "一般模态框",
        url: "/alert/modal",
        icon: "",
        children: [],
      },
      {
        id: "72",
        name: "提示框",
        url: "/alert/toast",
        icon: "",
        children: [],
      },
    ],
  },
  {
    id: "80",
    name: "菜单",
    url: "/menu",
    icon: "menu",
    children: [
      {
        id: "81",
        name: "菜单",
        url: "/menu/list",
        icon: "",
        children: [],
      },
      {
        id: "82",
        name: "树形菜单",
        url: "/menu/tree",
        icon: "",
        children: [],
      },
    ],
  },
  {
    id: "110",
    name: "工具",
    url: "/util",
    icon: "util",
    children: [
      {
        id: "111",
        name: "懒加载",
        url: "/util/routerLoad",
        icon: "",
        children: [],
      },
    ],
  },
  {
    id: "120",
    name: "动画",
    url: "/animate",
    icon: "animate",
    children: [
      {
        id: "121",
        name: "下拉收缩",
        url: "/animate/slide",
        icon: "",
        children: [],
      },
      {
        id: "122",
        name: "动画组件",
        url: "/animate/animate",
        icon: "",
        children: [],
      },
      {
        id: "123",
        name: "普通滚动条",
        url: "/animate/scroll",
        icon: "",
        children: [],
      },
    ]
  },
  {
    id: "90",
    name: "问题",
    url: "/problem",
    icon: "menu",
    children: [
      {
        id: "91",
        name: "两者平衡",
        url: "/problem/balence",
        icon: "",
        children: [],
      },
    ],
  },
  {
    id: "100",
    name: "拖拽",
    url: "/drag",
    icon: "menu",
    children: [
      {
        id: "101",
        name: "拖拽排序",
        url: "/drag/order",
        icon: "",
        children: [],
      },
    ],
  }
];
