const data = {
  code: 100,
  msg: "成功",
  data: {
    kpi_id: -2,
    kpi_name: null,
    par_id: null,
    type: null,
    kpi_weight: null,
    d_kpi_weight: null,
    children: [
      {
        kpi_id: 100000,
        kpi_name: "三级绩效指标",
        par_id: -2,
        type: 0,
        kpi_weight: "",
        d_kpi_weight: null,
        children: [
          {
            kpi_id: 100001,
            kpi_name: "医疗质量",
            par_id: 100000,
            type: 0,
            kpi_weight: "0.50",
            d_kpi_weight: null,
            children: [
              {
                kpi_id: 160001,
                kpi_name: "功能定位",
                par_id: 100001,
                type: 0,
                kpi_weight: "0.35",
                d_kpi_weight: null,
                children: [
                  {
                    kpi_id: 160032,
                    kpi_name: "门诊人次数与出院人次数比",
                    par_id: 160001,
                    type: 1,
                    kpi_weight: "0.15",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160045,
                    kpi_name: "日间手术占择期手术比例",
                    par_id: 160001,
                    type: 1,
                    kpi_weight: "0.15",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160053,
                    kpi_name: "出院患者手术占比",
                    par_id: 160001,
                    type: 1,
                    kpi_weight: "0.16",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160067,
                    kpi_name: "出院患者微创手术占比",
                    par_id: 160001,
                    type: 1,
                    kpi_weight: "0.14",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160073,
                    kpi_name: "出院患者四级手术比例",
                    par_id: 160001,
                    type: 1,
                    kpi_weight: "0.10",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160075,
                    kpi_name: "特需医疗服务量",
                    par_id: 160001,
                    type: 1,
                    kpi_weight: "0.05",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160191,
                    kpi_name: "全部医疗服务量",
                    par_id: 160001,
                    type: 1,
                    kpi_weight: "0.15",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160192,
                    kpi_name: "特需医疗服务占比",
                    par_id: 160001,
                    type: 1,
                    kpi_weight: "0.10",
                    d_kpi_weight: null,
                    children: [],
                  },
                ],
              },
              {
                kpi_id: 160003,
                kpi_name: "合理用药",
                par_id: 100001,
                type: 0,
                kpi_weight: "0.40",
                d_kpi_weight: null,
                children: [
                  {
                    kpi_id: 160092,
                    kpi_name: "点评处方占处方总数的比例",
                    par_id: 160003,
                    type: 1,
                    kpi_weight: "0.25",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160096,
                    kpi_name: "门诊患者基本药物处方占比",
                    par_id: 160003,
                    type: 1,
                    kpi_weight: "0.25",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160097,
                    kpi_name: "住院患者基本药物使用率",
                    par_id: 160003,
                    type: 1,
                    kpi_weight: "0.25",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160194,
                    kpi_name: "抗菌药物使用强度",
                    par_id: 160003,
                    type: 1,
                    kpi_weight: "0.05",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160195,
                    kpi_name: "基本药物采购品种数占比",
                    par_id: 160003,
                    type: 1,
                    kpi_weight: "0.05",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160198,
                    kpi_name: "国家组织药品集中采购中标药品使用比例",
                    par_id: 160003,
                    type: 1,
                    kpi_weight: "0.15",
                    d_kpi_weight: null,
                    children: [],
                  },
                ],
              },
              {
                kpi_id: 160036,
                kpi_name: "服务流程",
                par_id: 100001,
                type: 0,
                kpi_weight: "0.25",
                d_kpi_weight: null,
                children: [
                  {
                    kpi_id: 160037,
                    kpi_name: "门诊患者平均预约诊疗率",
                    par_id: 160036,
                    type: 1,
                    kpi_weight: "0.40",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160085,
                    kpi_name: "预约诊疗人次数",
                    par_id: 160036,
                    type: 1,
                    kpi_weight: "0.40",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160199,
                    kpi_name: "门诊患者预约后等待时间",
                    par_id: 160036,
                    type: 1,
                    kpi_weight: "0.20",
                    d_kpi_weight: null,
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            kpi_id: 100002,
            kpi_name: "运营效率",
            par_id: 100000,
            type: 0,
            kpi_weight: "0.25",
            d_kpi_weight: null,
            children: [
              {
                kpi_id: 160002,
                kpi_name: "收支结构",
                par_id: 100002,
                type: 0,
                kpi_weight: "0.30",
                d_kpi_weight: null,
                children: [
                  {
                    kpi_id: 160025,
                    kpi_name: "门诊收入中来自医保基金的比例",
                    par_id: 160002,
                    type: 1,
                    kpi_weight: "0.20",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160026,
                    kpi_name: "住院收入占医疗收入比例",
                    par_id: 160002,
                    type: 1,
                    kpi_weight: "0.10",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160042,
                    kpi_name: "住院收入中来自医保基金的比例",
                    par_id: 160002,
                    type: 1,
                    kpi_weight: "0.15",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160051,
                    kpi_name: "门诊收入占医疗收入比例",
                    par_id: 160002,
                    type: 1,
                    kpi_weight: "0.12",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160061,
                    kpi_name: "医疗服务收入占医疗收入比例",
                    par_id: 160002,
                    type: 1,
                    kpi_weight: "0.13",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160070,
                    kpi_name: "辅助用药收入占比",
                    par_id: 160002,
                    type: 1,
                    kpi_weight: "0.10",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160146,
                    kpi_name: "人员支出占业务支出比重",
                    par_id: 160002,
                    type: 1,
                    kpi_weight: "0.10",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160156,
                    kpi_name: "本年度资产负债率",
                    par_id: 160002,
                    type: 1,
                    kpi_weight: "0.10",
                    d_kpi_weight: null,
                    children: [],
                  },
                ],
              },
              {
                kpi_id: 160017,
                kpi_name: "经济管理",
                par_id: 100002,
                type: 0,
                kpi_weight: "0.45",
                d_kpi_weight: null,
                children: [
                  {
                    kpi_id: 160030,
                    kpi_name: "麻醉医师占比",
                    par_id: 160017,
                    type: 1,
                    kpi_weight: "0.18",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160033,
                    kpi_name: "医护比",
                    par_id: 160017,
                    type: 1,
                    kpi_weight: "0.22",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160170,
                    kpi_name: "儿科医师占比",
                    par_id: 160017,
                    type: 1,
                    kpi_weight: "0.10",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160171,
                    kpi_name: "重症医师占比",
                    par_id: 160017,
                    type: 1,
                    kpi_weight: "0.20",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160172,
                    kpi_name: "病理医师占比",
                    par_id: 160017,
                    type: 1,
                    kpi_weight: "0.15",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160173,
                    kpi_name: "中医医师占比",
                    par_id: 160017,
                    type: 1,
                    kpi_weight: "0.15",
                    d_kpi_weight: null,
                    children: [],
                  },
                ],
              },
              {
                kpi_id: 160048,
                kpi_name: "资源效率",
                par_id: 100002,
                type: 0,
                kpi_weight: "0.25",
                d_kpi_weight: null,
                children: [
                  {
                    kpi_id: 160052,
                    kpi_name: "每名执业医师日均住院工作负担",
                    par_id: 160048,
                    type: 1,
                    kpi_weight: "0.60",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160086,
                    kpi_name: "医院平均执业（助理）医师人数",
                    par_id: 160048,
                    type: 1,
                    kpi_weight: "0.40",
                    d_kpi_weight: null,
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            kpi_id: 100003,
            kpi_name: "持续发展",
            par_id: 100000,
            type: 0,
            kpi_weight: "0.25",
            d_kpi_weight: null,
            children: [
              {
                kpi_id: 160035,
                kpi_name: "人才培养",
                par_id: 100003,
                type: 0,
                kpi_weight: "0.50",
                d_kpi_weight: null,
                children: [
                  {
                    kpi_id: 160039,
                    kpi_name:
                      "医院接受其他医院（尤其是对口支援医院、医联体内医院）进修并返回原医院独立工作人数占比",
                    par_id: 160035,
                    type: 1,
                    kpi_weight: "0.25",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160043,
                    kpi_name: "医院住院医师首次参加医师资格考试通过率",
                    par_id: 160035,
                    type: 1,
                    kpi_weight: "0.25",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160123,
                    kpi_name: "承担医学教育的人数",
                    par_id: 160035,
                    type: 1,
                    kpi_weight: "0.20",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160124,
                    kpi_name: "发表教学论文的数量",
                    par_id: 160035,
                    type: 1,
                    kpi_weight: "0.30",
                    d_kpi_weight: null,
                    children: [],
                  },
                ],
              },
              {
                kpi_id: 160049,
                kpi_name: "学科建设",
                par_id: 100003,
                type: 0,
                kpi_weight: "0.50",
                d_kpi_weight: null,
                children: [
                  {
                    kpi_id: 160055,
                    kpi_name: "每百名卫生技术人员科研成果转化金额",
                    par_id: 160049,
                    type: 1,
                    kpi_weight: "0.50",
                    d_kpi_weight: null,
                    children: [],
                  },
                  {
                    kpi_id: 160115,
                    kpi_name: "技术合同总金额",
                    par_id: 160049,
                    type: 1,
                    kpi_weight: "0.50",
                    d_kpi_weight: null,
                    children: [],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
};
export { data };
